<?php
$v_params = $this->getParams();
$o_contato = $v_params['o_contato'];
$v_telefones = $v_params['v_telefones'];
require_once("header.phtml");
?>

<body>
    <div id="tblcontc" align="center" >

        <th colspan='3'align="center">Contacto</th>
        <table class="table" align="center">
        <thead class="thead-dark">
            <tr scope="col">

            <tr class="thead-dark">

                <td> ID </td>
                <td>Nombre</td>
                <td>E-mail</td>

            </tr>
            <tr>
                <td><?php echo $o_contato->getId()?></td>
                <td><?php echo $o_contato->getNome()?></td>
                <td><?php echo $o_contato->getEmail()?></td>
            </tr>
        </table>
        <br />
<tr>
        <div id="tblcontc" align="center" >
            <th colspan='4'align="center">TELEFONO</th>

            <table class="table" align="center">
                <thead class="thead-dark">

                <tr class="thead-dark">
                    <th>ID</th>
                    <th>Cod</th>
                    <th>Telefono</th>
                    <th>Acciones</th>
                </tr>
            </tr>
            <?php
            foreach($v_telefones AS $o_telefone)
            { 
                ?>
                <tr>
                    <td>
                        <?php echo $o_telefone->getId()?>
                    </td>
                    <td>
                        <?php echo $o_telefone->getDDD()?>
                    </td>
                    <td>
                        <?php echo $o_telefone->getTelefone()?>
                    </td>
                    <td>
                        <a href='?controle=Telefone&acao=apagarTelefone&in_con=<?php echo $o_contato->getId()?>&in_tel=<?php echo $o_telefone->getId()?>'><i class="fas fa-trash-alt"></i</a>
                        &nbsp;&nbsp;
                        <a href='?controle=Telefone&acao=manterTelefone&in_con=<?php echo $o_contato->getId()?>&in_tel=<?php echo $o_telefone->getId()?>'><i class="fas fa-edit"></i></a>
                        &nbsp;&nbsp;
                    </td>
                </tr>
                <?php
            } 
            ?>
        </table>
        <br />
            <a href='?controle=Index'><i class="far fa-arrow-alt-circle-left"></i><h> volver</h></a>
            <a href='?controle=Telefone&acao=manterTelefone&in_con=<?php echo $o_contato->getId()?>'><i class="far fa-address-book"></i><h>Agregar</h></a>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
</body>
</html>
